# Generated by Django 6.0 on 2025-12-15 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="review_test",
            new_name="review_text",
        ),
    ]
